#Shared configuration for the other docker-compose files
version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_USER=test
      - MONGO_PASSWORD=123456
    volumes:
      #Local directory / Inner container directory
      - ./:/app
      - /app/node_modules
    command: npm run dev

#Remote image
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      # named volume config 1/2
      - mongo-db:/data/db
    ports:
      - 2017:27017
volumes:
# mongo named volume config 2/2
  mongo-db: